apiVersion: apps/v1
kind: Deployment
metadata:
  name: apc-userservice
  namespace: apc
  labels:
    app: userservice
    category: backend
spec:
  selector:
    matchLabels:
      app: userservice
  revisionHistoryLimit: 2
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: userservice
        category: backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: userservice-pod
          image:
            {{- required "Docker repo required" .Values.dockerRepository | indent 1 -}}
             /services/userservice:
            {{- .Values.releaseLabel }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: 256M
              cpu: 100m
            limits:
              memory: 1G
              cpu: 200m
          env:
            - name: TABLE_STORAGE
              valueFrom:
                secretKeyRef:
                  key: usersTableConnectionString
                  name: general-secrets
