apiVersion: v1
kind: Secret
metadata:
  namespace: apc
  name: general-secrets
type: Opaque
stringData:
  cosmosConnectionString: <redacted>
  blobConnectionString: <redacted>
  usersTableConnectionString: <redacted>
  googleId: <redacted>
  googleSecret: <redacted>
---
apiVersion: v1
kind: Secret
metadata:
  namespace: apc
  name: https-certs
type: kubernetes.io/tls
stringData:
  tls.crt: |
        <redacted>
  tls.key: |
        <redacted>
